build_environment: ubuntu1404
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install -d api

script:
  - curl -s http://localhost/api/ && sudo cat /var/log/apache2/error.log && curl -s http://localhost/api/
  - api/vendor/bin/phpunit --configuration ./api/phpunit.xml --verbose
