language: php

php:
  - 5.4
  - 5.5
  - 5.6
  # - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - sh ./.travis/install_server.sh

script:
  - ./vendor/bin/phpunit --configuration ./tests/phpunit.xml --testsuite unit
